// Code generated by protoc-gen-go.
// source: ots_api.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	ots_api.proto

It has these top-level messages:
	Error
	ColumnSchema
	ColumnValue
	Column
	Row
	TableMeta
	Condition
	CapacityUnit
	ReservedThroughputDetails
	ReservedThroughput
	ConsumedCapacity
	CreateTableRequest
	CreateTableResponse
	UpdateTableRequest
	UpdateTableResponse
	DescribeTableRequest
	DescribeTableResponse
	ListTableRequest
	ListTableResponse
	DeleteTableRequest
	DeleteTableResponse
	GetRowRequest
	GetRowResponse
	ColumnUpdate
	UpdateRowRequest
	UpdateRowResponse
	PutRowRequest
	PutRowResponse
	DeleteRowRequest
	DeleteRowResponse
	RowInBatchGetRowRequest
	TableInBatchGetRowRequest
	BatchGetRowRequest
	RowInBatchGetRowResponse
	TableInBatchGetRowResponse
	BatchGetRowResponse
	PutRowInBatchWriteRowRequest
	UpdateRowInBatchWriteRowRequest
	DeleteRowInBatchWriteRowRequest
	TableInBatchWriteRowRequest
	BatchWriteRowRequest
	RowInBatchWriteRowResponse
	TableInBatchWriteRowResponse
	BatchWriteRowResponse
	GetRangeRequest
	GetRangeResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ColumnType int32

const (
	ColumnType_INF_MIN ColumnType = 0
	ColumnType_INF_MAX ColumnType = 1
	ColumnType_INTEGER ColumnType = 2
	ColumnType_STRING  ColumnType = 3
	ColumnType_BOOLEAN ColumnType = 4
	ColumnType_DOUBLE  ColumnType = 5
	ColumnType_BINARY  ColumnType = 6
)

var ColumnType_name = map[int32]string{
	0: "INF_MIN",
	1: "INF_MAX",
	2: "INTEGER",
	3: "STRING",
	4: "BOOLEAN",
	5: "DOUBLE",
	6: "BINARY",
}
var ColumnType_value = map[string]int32{
	"INF_MIN": 0,
	"INF_MAX": 1,
	"INTEGER": 2,
	"STRING":  3,
	"BOOLEAN": 4,
	"DOUBLE":  5,
	"BINARY":  6,
}

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}
func (x ColumnType) String() string {
	return proto.EnumName(ColumnType_name, int32(x))
}
func (x *ColumnType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ColumnType_value, data, "ColumnType")
	if err != nil {
		return err
	}
	*x = ColumnType(value)
	return nil
}
func (ColumnType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RowExistenceExpectation int32

const (
	RowExistenceExpectation_IGNORE           RowExistenceExpectation = 0
	RowExistenceExpectation_EXPECT_EXIST     RowExistenceExpectation = 1
	RowExistenceExpectation_EXPECT_NOT_EXIST RowExistenceExpectation = 2
)

var RowExistenceExpectation_name = map[int32]string{
	0: "IGNORE",
	1: "EXPECT_EXIST",
	2: "EXPECT_NOT_EXIST",
}
var RowExistenceExpectation_value = map[string]int32{
	"IGNORE":           0,
	"EXPECT_EXIST":     1,
	"EXPECT_NOT_EXIST": 2,
}

func (x RowExistenceExpectation) Enum() *RowExistenceExpectation {
	p := new(RowExistenceExpectation)
	*p = x
	return p
}
func (x RowExistenceExpectation) String() string {
	return proto.EnumName(RowExistenceExpectation_name, int32(x))
}
func (x *RowExistenceExpectation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RowExistenceExpectation_value, data, "RowExistenceExpectation")
	if err != nil {
		return err
	}
	*x = RowExistenceExpectation(value)
	return nil
}
func (RowExistenceExpectation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// UpdateRow
type OperationType int32

const (
	OperationType_PUT    OperationType = 1
	OperationType_DELETE OperationType = 2
)

var OperationType_name = map[int32]string{
	1: "PUT",
	2: "DELETE",
}
var OperationType_value = map[string]int32{
	"PUT":    1,
	"DELETE": 2,
}

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}
func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}
func (x *OperationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OperationType_value, data, "OperationType")
	if err != nil {
		return err
	}
	*x = OperationType(value)
	return nil
}
func (OperationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// GetRange
type Direction int32

const (
	Direction_FORWARD  Direction = 0
	Direction_BACKWARD Direction = 1
)

var Direction_name = map[int32]string{
	0: "FORWARD",
	1: "BACKWARD",
}
var Direction_value = map[string]int32{
	"FORWARD":  0,
	"BACKWARD": 1,
}

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}
func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}
func (x *Direction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Direction_value, data, "Direction")
	if err != nil {
		return err
	}
	*x = Direction(value)
	return nil
}
func (Direction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Error struct {
	Code             *string `protobuf:"bytes,1,req,name=code" json:"code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ColumnSchema struct {
	Name             *string     `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Type             *ColumnType `protobuf:"varint,2,req,name=type,enum=pb.ColumnType" json:"type,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ColumnSchema) Reset()                    { *m = ColumnSchema{} }
func (m *ColumnSchema) String() string            { return proto.CompactTextString(m) }
func (*ColumnSchema) ProtoMessage()               {}
func (*ColumnSchema) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ColumnSchema) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ColumnSchema) GetType() ColumnType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ColumnType_INF_MIN
}

type ColumnValue struct {
	Type             *ColumnType `protobuf:"varint,1,req,name=type,enum=pb.ColumnType" json:"type,omitempty"`
	VInt             *int64      `protobuf:"varint,2,opt,name=v_int" json:"v_int,omitempty"`
	VString          *string     `protobuf:"bytes,3,opt,name=v_string" json:"v_string,omitempty"`
	VBool            *bool       `protobuf:"varint,4,opt,name=v_bool" json:"v_bool,omitempty"`
	VDouble          *float64    `protobuf:"fixed64,5,opt,name=v_double" json:"v_double,omitempty"`
	VBinary          []byte      `protobuf:"bytes,6,opt,name=v_binary" json:"v_binary,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ColumnValue) Reset()                    { *m = ColumnValue{} }
func (m *ColumnValue) String() string            { return proto.CompactTextString(m) }
func (*ColumnValue) ProtoMessage()               {}
func (*ColumnValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ColumnValue) GetType() ColumnType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ColumnType_INF_MIN
}

func (m *ColumnValue) GetVInt() int64 {
	if m != nil && m.VInt != nil {
		return *m.VInt
	}
	return 0
}

func (m *ColumnValue) GetVString() string {
	if m != nil && m.VString != nil {
		return *m.VString
	}
	return ""
}

func (m *ColumnValue) GetVBool() bool {
	if m != nil && m.VBool != nil {
		return *m.VBool
	}
	return false
}

func (m *ColumnValue) GetVDouble() float64 {
	if m != nil && m.VDouble != nil {
		return *m.VDouble
	}
	return 0
}

func (m *ColumnValue) GetVBinary() []byte {
	if m != nil {
		return m.VBinary
	}
	return nil
}

type Column struct {
	Name             *string      `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *ColumnValue `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Column) Reset()                    { *m = Column{} }
func (m *Column) String() string            { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()               {}
func (*Column) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Column) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Column) GetValue() *ColumnValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type Row struct {
	PrimaryKeyColumns []*Column `protobuf:"bytes,1,rep,name=primary_key_columns" json:"primary_key_columns,omitempty"`
	AttributeColumns  []*Column `protobuf:"bytes,2,rep,name=attribute_columns" json:"attribute_columns,omitempty"`
	XXX_unrecognized  []byte    `json:"-"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Row) GetPrimaryKeyColumns() []*Column {
	if m != nil {
		return m.PrimaryKeyColumns
	}
	return nil
}

func (m *Row) GetAttributeColumns() []*Column {
	if m != nil {
		return m.AttributeColumns
	}
	return nil
}

type TableMeta struct {
	TableName        *string         `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PrimaryKey       []*ColumnSchema `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *TableMeta) Reset()                    { *m = TableMeta{} }
func (m *TableMeta) String() string            { return proto.CompactTextString(m) }
func (*TableMeta) ProtoMessage()               {}
func (*TableMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TableMeta) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableMeta) GetPrimaryKey() []*ColumnSchema {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

type Condition struct {
	RowExistence     *RowExistenceExpectation `protobuf:"varint,1,req,name=row_existence,enum=pb.RowExistenceExpectation" json:"row_existence,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *Condition) Reset()                    { *m = Condition{} }
func (m *Condition) String() string            { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()               {}
func (*Condition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Condition) GetRowExistence() RowExistenceExpectation {
	if m != nil && m.RowExistence != nil {
		return *m.RowExistence
	}
	return RowExistenceExpectation_IGNORE
}

type CapacityUnit struct {
	Read             *int32 `protobuf:"varint,1,opt,name=read" json:"read,omitempty"`
	Write            *int32 `protobuf:"varint,2,opt,name=write" json:"write,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CapacityUnit) Reset()                    { *m = CapacityUnit{} }
func (m *CapacityUnit) String() string            { return proto.CompactTextString(m) }
func (*CapacityUnit) ProtoMessage()               {}
func (*CapacityUnit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CapacityUnit) GetRead() int32 {
	if m != nil && m.Read != nil {
		return *m.Read
	}
	return 0
}

func (m *CapacityUnit) GetWrite() int32 {
	if m != nil && m.Write != nil {
		return *m.Write
	}
	return 0
}

type ReservedThroughputDetails struct {
	CapacityUnit           *CapacityUnit `protobuf:"bytes,1,req,name=capacity_unit" json:"capacity_unit,omitempty"`
	LastIncreaseTime       *int64        `protobuf:"varint,2,req,name=last_increase_time" json:"last_increase_time,omitempty"`
	LastDecreaseTime       *int64        `protobuf:"varint,3,opt,name=last_decrease_time" json:"last_decrease_time,omitempty"`
	NumberOfDecreasesToday *int32        `protobuf:"varint,4,req,name=number_of_decreases_today" json:"number_of_decreases_today,omitempty"`
	XXX_unrecognized       []byte        `json:"-"`
}

func (m *ReservedThroughputDetails) Reset()                    { *m = ReservedThroughputDetails{} }
func (m *ReservedThroughputDetails) String() string            { return proto.CompactTextString(m) }
func (*ReservedThroughputDetails) ProtoMessage()               {}
func (*ReservedThroughputDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReservedThroughputDetails) GetCapacityUnit() *CapacityUnit {
	if m != nil {
		return m.CapacityUnit
	}
	return nil
}

func (m *ReservedThroughputDetails) GetLastIncreaseTime() int64 {
	if m != nil && m.LastIncreaseTime != nil {
		return *m.LastIncreaseTime
	}
	return 0
}

func (m *ReservedThroughputDetails) GetLastDecreaseTime() int64 {
	if m != nil && m.LastDecreaseTime != nil {
		return *m.LastDecreaseTime
	}
	return 0
}

func (m *ReservedThroughputDetails) GetNumberOfDecreasesToday() int32 {
	if m != nil && m.NumberOfDecreasesToday != nil {
		return *m.NumberOfDecreasesToday
	}
	return 0
}

type ReservedThroughput struct {
	CapacityUnit     *CapacityUnit `protobuf:"bytes,1,req,name=capacity_unit" json:"capacity_unit,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ReservedThroughput) Reset()                    { *m = ReservedThroughput{} }
func (m *ReservedThroughput) String() string            { return proto.CompactTextString(m) }
func (*ReservedThroughput) ProtoMessage()               {}
func (*ReservedThroughput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ReservedThroughput) GetCapacityUnit() *CapacityUnit {
	if m != nil {
		return m.CapacityUnit
	}
	return nil
}

type ConsumedCapacity struct {
	CapacityUnit     *CapacityUnit `protobuf:"bytes,1,req,name=capacity_unit" json:"capacity_unit,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ConsumedCapacity) Reset()                    { *m = ConsumedCapacity{} }
func (m *ConsumedCapacity) String() string            { return proto.CompactTextString(m) }
func (*ConsumedCapacity) ProtoMessage()               {}
func (*ConsumedCapacity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ConsumedCapacity) GetCapacityUnit() *CapacityUnit {
	if m != nil {
		return m.CapacityUnit
	}
	return nil
}

// CreateTable
type CreateTableRequest struct {
	TableMeta          *TableMeta          `protobuf:"bytes,1,req,name=table_meta" json:"table_meta,omitempty"`
	ReservedThroughput *ReservedThroughput `protobuf:"bytes,2,req,name=reserved_throughput" json:"reserved_throughput,omitempty"`
	XXX_unrecognized   []byte              `json:"-"`
}

func (m *CreateTableRequest) Reset()                    { *m = CreateTableRequest{} }
func (m *CreateTableRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTableRequest) ProtoMessage()               {}
func (*CreateTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateTableRequest) GetTableMeta() *TableMeta {
	if m != nil {
		return m.TableMeta
	}
	return nil
}

func (m *CreateTableRequest) GetReservedThroughput() *ReservedThroughput {
	if m != nil {
		return m.ReservedThroughput
	}
	return nil
}

type CreateTableResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateTableResponse) Reset()                    { *m = CreateTableResponse{} }
func (m *CreateTableResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTableResponse) ProtoMessage()               {}
func (*CreateTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type UpdateTableRequest struct {
	TableName          *string             `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	ReservedThroughput *ReservedThroughput `protobuf:"bytes,2,req,name=reserved_throughput" json:"reserved_throughput,omitempty"`
	XXX_unrecognized   []byte              `json:"-"`
}

func (m *UpdateTableRequest) Reset()                    { *m = UpdateTableRequest{} }
func (m *UpdateTableRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateTableRequest) ProtoMessage()               {}
func (*UpdateTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *UpdateTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *UpdateTableRequest) GetReservedThroughput() *ReservedThroughput {
	if m != nil {
		return m.ReservedThroughput
	}
	return nil
}

type UpdateTableResponse struct {
	ReservedThroughputDetails *ReservedThroughputDetails `protobuf:"bytes,1,req,name=reserved_throughput_details" json:"reserved_throughput_details,omitempty"`
	XXX_unrecognized          []byte                     `json:"-"`
}

func (m *UpdateTableResponse) Reset()                    { *m = UpdateTableResponse{} }
func (m *UpdateTableResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateTableResponse) ProtoMessage()               {}
func (*UpdateTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UpdateTableResponse) GetReservedThroughputDetails() *ReservedThroughputDetails {
	if m != nil {
		return m.ReservedThroughputDetails
	}
	return nil
}

// DescribeTable
type DescribeTableRequest struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DescribeTableRequest) Reset()                    { *m = DescribeTableRequest{} }
func (m *DescribeTableRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeTableRequest) ProtoMessage()               {}
func (*DescribeTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DescribeTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type DescribeTableResponse struct {
	TableMeta                 *TableMeta                 `protobuf:"bytes,1,req,name=table_meta" json:"table_meta,omitempty"`
	ReservedThroughputDetails *ReservedThroughputDetails `protobuf:"bytes,2,req,name=reserved_throughput_details" json:"reserved_throughput_details,omitempty"`
	XXX_unrecognized          []byte                     `json:"-"`
}

func (m *DescribeTableResponse) Reset()                    { *m = DescribeTableResponse{} }
func (m *DescribeTableResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeTableResponse) ProtoMessage()               {}
func (*DescribeTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *DescribeTableResponse) GetTableMeta() *TableMeta {
	if m != nil {
		return m.TableMeta
	}
	return nil
}

func (m *DescribeTableResponse) GetReservedThroughputDetails() *ReservedThroughputDetails {
	if m != nil {
		return m.ReservedThroughputDetails
	}
	return nil
}

// ListTable
type ListTableRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ListTableRequest) Reset()                    { *m = ListTableRequest{} }
func (m *ListTableRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTableRequest) ProtoMessage()               {}
func (*ListTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type ListTableResponse struct {
	TableNames       []string `protobuf:"bytes,1,rep,name=table_names" json:"table_names,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ListTableResponse) Reset()                    { *m = ListTableResponse{} }
func (m *ListTableResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTableResponse) ProtoMessage()               {}
func (*ListTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ListTableResponse) GetTableNames() []string {
	if m != nil {
		return m.TableNames
	}
	return nil
}

// DeleteTable
type DeleteTableRequest struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteTableRequest) Reset()                    { *m = DeleteTableRequest{} }
func (m *DeleteTableRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTableRequest) ProtoMessage()               {}
func (*DeleteTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DeleteTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type DeleteTableResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteTableResponse) Reset()                    { *m = DeleteTableResponse{} }
func (m *DeleteTableResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteTableResponse) ProtoMessage()               {}
func (*DeleteTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

// GetRow
type GetRowRequest struct {
	TableName        *string   `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PrimaryKey       []*Column `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	ColumnsToGet     []string  `protobuf:"bytes,3,rep,name=columns_to_get" json:"columns_to_get,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GetRowRequest) Reset()                    { *m = GetRowRequest{} }
func (m *GetRowRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRowRequest) ProtoMessage()               {}
func (*GetRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *GetRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *GetRowRequest) GetColumnsToGet() []string {
	if m != nil {
		return m.ColumnsToGet
	}
	return nil
}

type GetRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	Row              *Row              `protobuf:"bytes,2,req,name=row" json:"row,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetRowResponse) Reset()                    { *m = GetRowResponse{} }
func (m *GetRowResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRowResponse) ProtoMessage()               {}
func (*GetRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GetRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *GetRowResponse) GetRow() *Row {
	if m != nil {
		return m.Row
	}
	return nil
}

type ColumnUpdate struct {
	Type             *OperationType `protobuf:"varint,1,req,name=type,enum=pb.OperationType" json:"type,omitempty"`
	Name             *string        `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Value            *ColumnValue   `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ColumnUpdate) Reset()                    { *m = ColumnUpdate{} }
func (m *ColumnUpdate) String() string            { return proto.CompactTextString(m) }
func (*ColumnUpdate) ProtoMessage()               {}
func (*ColumnUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ColumnUpdate) GetType() OperationType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return OperationType_PUT
}

func (m *ColumnUpdate) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ColumnUpdate) GetValue() *ColumnValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type UpdateRowRequest struct {
	TableName        *string         `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Condition        *Condition      `protobuf:"bytes,2,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column       `protobuf:"bytes,3,rep,name=primary_key" json:"primary_key,omitempty"`
	AttributeColumns []*ColumnUpdate `protobuf:"bytes,4,rep,name=attribute_columns" json:"attribute_columns,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *UpdateRowRequest) Reset()                    { *m = UpdateRowRequest{} }
func (m *UpdateRowRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRowRequest) ProtoMessage()               {}
func (*UpdateRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *UpdateRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *UpdateRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *UpdateRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *UpdateRowRequest) GetAttributeColumns() []*ColumnUpdate {
	if m != nil {
		return m.AttributeColumns
	}
	return nil
}

type UpdateRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *UpdateRowResponse) Reset()                    { *m = UpdateRowResponse{} }
func (m *UpdateRowResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateRowResponse) ProtoMessage()               {}
func (*UpdateRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *UpdateRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

// PutRow
type PutRowRequest struct {
	TableName        *string    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Condition        *Condition `protobuf:"bytes,2,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column  `protobuf:"bytes,3,rep,name=primary_key" json:"primary_key,omitempty"`
	AttributeColumns []*Column  `protobuf:"bytes,4,rep,name=attribute_columns" json:"attribute_columns,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PutRowRequest) Reset()                    { *m = PutRowRequest{} }
func (m *PutRowRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRowRequest) ProtoMessage()               {}
func (*PutRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *PutRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *PutRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *PutRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *PutRowRequest) GetAttributeColumns() []*Column {
	if m != nil {
		return m.AttributeColumns
	}
	return nil
}

type PutRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PutRowResponse) Reset()                    { *m = PutRowResponse{} }
func (m *PutRowResponse) String() string            { return proto.CompactTextString(m) }
func (*PutRowResponse) ProtoMessage()               {}
func (*PutRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *PutRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

// DeleteRow
type DeleteRowRequest struct {
	TableName        *string    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Condition        *Condition `protobuf:"bytes,2,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column  `protobuf:"bytes,3,rep,name=primary_key" json:"primary_key,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *DeleteRowRequest) Reset()                    { *m = DeleteRowRequest{} }
func (m *DeleteRowRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRowRequest) ProtoMessage()               {}
func (*DeleteRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *DeleteRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *DeleteRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *DeleteRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

type DeleteRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DeleteRowResponse) Reset()                    { *m = DeleteRowResponse{} }
func (m *DeleteRowResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteRowResponse) ProtoMessage()               {}
func (*DeleteRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *DeleteRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

// BatchGetRow
type RowInBatchGetRowRequest struct {
	PrimaryKey       []*Column `protobuf:"bytes,1,rep,name=primary_key" json:"primary_key,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *RowInBatchGetRowRequest) Reset()                    { *m = RowInBatchGetRowRequest{} }
func (m *RowInBatchGetRowRequest) String() string            { return proto.CompactTextString(m) }
func (*RowInBatchGetRowRequest) ProtoMessage()               {}
func (*RowInBatchGetRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *RowInBatchGetRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

type TableInBatchGetRowRequest struct {
	TableName        *string                    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Rows             []*RowInBatchGetRowRequest `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	ColumnsToGet     []string                   `protobuf:"bytes,3,rep,name=columns_to_get" json:"columns_to_get,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *TableInBatchGetRowRequest) Reset()                    { *m = TableInBatchGetRowRequest{} }
func (m *TableInBatchGetRowRequest) String() string            { return proto.CompactTextString(m) }
func (*TableInBatchGetRowRequest) ProtoMessage()               {}
func (*TableInBatchGetRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *TableInBatchGetRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchGetRowRequest) GetRows() []*RowInBatchGetRowRequest {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *TableInBatchGetRowRequest) GetColumnsToGet() []string {
	if m != nil {
		return m.ColumnsToGet
	}
	return nil
}

type BatchGetRowRequest struct {
	Tables           []*TableInBatchGetRowRequest `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *BatchGetRowRequest) Reset()                    { *m = BatchGetRowRequest{} }
func (m *BatchGetRowRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchGetRowRequest) ProtoMessage()               {}
func (*BatchGetRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *BatchGetRowRequest) GetTables() []*TableInBatchGetRowRequest {
	if m != nil {
		return m.Tables
	}
	return nil
}

type RowInBatchGetRowResponse struct {
	IsOk             *bool             `protobuf:"varint,1,req,name=is_ok,def=1" json:"is_ok,omitempty"`
	Error            *Error            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Consumed         *ConsumedCapacity `protobuf:"bytes,3,opt,name=consumed" json:"consumed,omitempty"`
	Row              *Row              `protobuf:"bytes,4,opt,name=row" json:"row,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RowInBatchGetRowResponse) Reset()                    { *m = RowInBatchGetRowResponse{} }
func (m *RowInBatchGetRowResponse) String() string            { return proto.CompactTextString(m) }
func (*RowInBatchGetRowResponse) ProtoMessage()               {}
func (*RowInBatchGetRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

const Default_RowInBatchGetRowResponse_IsOk bool = true

func (m *RowInBatchGetRowResponse) GetIsOk() bool {
	if m != nil && m.IsOk != nil {
		return *m.IsOk
	}
	return Default_RowInBatchGetRowResponse_IsOk
}

func (m *RowInBatchGetRowResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RowInBatchGetRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *RowInBatchGetRowResponse) GetRow() *Row {
	if m != nil {
		return m.Row
	}
	return nil
}

type TableInBatchGetRowResponse struct {
	TableName        *string                     `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Rows             []*RowInBatchGetRowResponse `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *TableInBatchGetRowResponse) Reset()                    { *m = TableInBatchGetRowResponse{} }
func (m *TableInBatchGetRowResponse) String() string            { return proto.CompactTextString(m) }
func (*TableInBatchGetRowResponse) ProtoMessage()               {}
func (*TableInBatchGetRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *TableInBatchGetRowResponse) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchGetRowResponse) GetRows() []*RowInBatchGetRowResponse {
	if m != nil {
		return m.Rows
	}
	return nil
}

type BatchGetRowResponse struct {
	Tables           []*TableInBatchGetRowResponse `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *BatchGetRowResponse) Reset()                    { *m = BatchGetRowResponse{} }
func (m *BatchGetRowResponse) String() string            { return proto.CompactTextString(m) }
func (*BatchGetRowResponse) ProtoMessage()               {}
func (*BatchGetRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *BatchGetRowResponse) GetTables() []*TableInBatchGetRowResponse {
	if m != nil {
		return m.Tables
	}
	return nil
}

// BatchWriteRow
type PutRowInBatchWriteRowRequest struct {
	Condition        *Condition `protobuf:"bytes,1,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column  `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	AttributeColumns []*Column  `protobuf:"bytes,3,rep,name=attribute_columns" json:"attribute_columns,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PutRowInBatchWriteRowRequest) Reset()                    { *m = PutRowInBatchWriteRowRequest{} }
func (m *PutRowInBatchWriteRowRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRowInBatchWriteRowRequest) ProtoMessage()               {}
func (*PutRowInBatchWriteRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *PutRowInBatchWriteRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *PutRowInBatchWriteRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *PutRowInBatchWriteRowRequest) GetAttributeColumns() []*Column {
	if m != nil {
		return m.AttributeColumns
	}
	return nil
}

type UpdateRowInBatchWriteRowRequest struct {
	Condition        *Condition      `protobuf:"bytes,1,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column       `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	AttributeColumns []*ColumnUpdate `protobuf:"bytes,3,rep,name=attribute_columns" json:"attribute_columns,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *UpdateRowInBatchWriteRowRequest) Reset()         { *m = UpdateRowInBatchWriteRowRequest{} }
func (m *UpdateRowInBatchWriteRowRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRowInBatchWriteRowRequest) ProtoMessage()    {}
func (*UpdateRowInBatchWriteRowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{37}
}

func (m *UpdateRowInBatchWriteRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *UpdateRowInBatchWriteRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *UpdateRowInBatchWriteRowRequest) GetAttributeColumns() []*ColumnUpdate {
	if m != nil {
		return m.AttributeColumns
	}
	return nil
}

type DeleteRowInBatchWriteRowRequest struct {
	Condition        *Condition `protobuf:"bytes,1,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column  `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *DeleteRowInBatchWriteRowRequest) Reset()         { *m = DeleteRowInBatchWriteRowRequest{} }
func (m *DeleteRowInBatchWriteRowRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRowInBatchWriteRowRequest) ProtoMessage()    {}
func (*DeleteRowInBatchWriteRowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{38}
}

func (m *DeleteRowInBatchWriteRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *DeleteRowInBatchWriteRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

type TableInBatchWriteRowRequest struct {
	TableName        *string                            `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PutRows          []*PutRowInBatchWriteRowRequest    `protobuf:"bytes,2,rep,name=put_rows" json:"put_rows,omitempty"`
	UpdateRows       []*UpdateRowInBatchWriteRowRequest `protobuf:"bytes,3,rep,name=update_rows" json:"update_rows,omitempty"`
	DeleteRows       []*DeleteRowInBatchWriteRowRequest `protobuf:"bytes,4,rep,name=delete_rows" json:"delete_rows,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *TableInBatchWriteRowRequest) Reset()                    { *m = TableInBatchWriteRowRequest{} }
func (m *TableInBatchWriteRowRequest) String() string            { return proto.CompactTextString(m) }
func (*TableInBatchWriteRowRequest) ProtoMessage()               {}
func (*TableInBatchWriteRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *TableInBatchWriteRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchWriteRowRequest) GetPutRows() []*PutRowInBatchWriteRowRequest {
	if m != nil {
		return m.PutRows
	}
	return nil
}

func (m *TableInBatchWriteRowRequest) GetUpdateRows() []*UpdateRowInBatchWriteRowRequest {
	if m != nil {
		return m.UpdateRows
	}
	return nil
}

func (m *TableInBatchWriteRowRequest) GetDeleteRows() []*DeleteRowInBatchWriteRowRequest {
	if m != nil {
		return m.DeleteRows
	}
	return nil
}

type BatchWriteRowRequest struct {
	Tables           []*TableInBatchWriteRowRequest `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *BatchWriteRowRequest) Reset()                    { *m = BatchWriteRowRequest{} }
func (m *BatchWriteRowRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchWriteRowRequest) ProtoMessage()               {}
func (*BatchWriteRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *BatchWriteRowRequest) GetTables() []*TableInBatchWriteRowRequest {
	if m != nil {
		return m.Tables
	}
	return nil
}

type RowInBatchWriteRowResponse struct {
	IsOk             *bool             `protobuf:"varint,1,req,name=is_ok,def=1" json:"is_ok,omitempty"`
	Error            *Error            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Consumed         *ConsumedCapacity `protobuf:"bytes,3,opt,name=consumed" json:"consumed,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RowInBatchWriteRowResponse) Reset()                    { *m = RowInBatchWriteRowResponse{} }
func (m *RowInBatchWriteRowResponse) String() string            { return proto.CompactTextString(m) }
func (*RowInBatchWriteRowResponse) ProtoMessage()               {}
func (*RowInBatchWriteRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

const Default_RowInBatchWriteRowResponse_IsOk bool = true

func (m *RowInBatchWriteRowResponse) GetIsOk() bool {
	if m != nil && m.IsOk != nil {
		return *m.IsOk
	}
	return Default_RowInBatchWriteRowResponse_IsOk
}

func (m *RowInBatchWriteRowResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RowInBatchWriteRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

type TableInBatchWriteRowResponse struct {
	TableName        *string                       `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PutRows          []*RowInBatchWriteRowResponse `protobuf:"bytes,2,rep,name=put_rows" json:"put_rows,omitempty"`
	UpdateRows       []*RowInBatchWriteRowResponse `protobuf:"bytes,3,rep,name=update_rows" json:"update_rows,omitempty"`
	DeleteRows       []*RowInBatchWriteRowResponse `protobuf:"bytes,4,rep,name=delete_rows" json:"delete_rows,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *TableInBatchWriteRowResponse) Reset()                    { *m = TableInBatchWriteRowResponse{} }
func (m *TableInBatchWriteRowResponse) String() string            { return proto.CompactTextString(m) }
func (*TableInBatchWriteRowResponse) ProtoMessage()               {}
func (*TableInBatchWriteRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *TableInBatchWriteRowResponse) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchWriteRowResponse) GetPutRows() []*RowInBatchWriteRowResponse {
	if m != nil {
		return m.PutRows
	}
	return nil
}

func (m *TableInBatchWriteRowResponse) GetUpdateRows() []*RowInBatchWriteRowResponse {
	if m != nil {
		return m.UpdateRows
	}
	return nil
}

func (m *TableInBatchWriteRowResponse) GetDeleteRows() []*RowInBatchWriteRowResponse {
	if m != nil {
		return m.DeleteRows
	}
	return nil
}

type BatchWriteRowResponse struct {
	Tables           []*TableInBatchWriteRowResponse `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *BatchWriteRowResponse) Reset()                    { *m = BatchWriteRowResponse{} }
func (m *BatchWriteRowResponse) String() string            { return proto.CompactTextString(m) }
func (*BatchWriteRowResponse) ProtoMessage()               {}
func (*BatchWriteRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *BatchWriteRowResponse) GetTables() []*TableInBatchWriteRowResponse {
	if m != nil {
		return m.Tables
	}
	return nil
}

type GetRangeRequest struct {
	TableName                *string    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Direction                *Direction `protobuf:"varint,2,req,name=direction,enum=pb.Direction" json:"direction,omitempty"`
	ColumnsToGet             []string   `protobuf:"bytes,3,rep,name=columns_to_get" json:"columns_to_get,omitempty"`
	Limit                    *int32     `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
	InclusiveStartPrimaryKey []*Column  `protobuf:"bytes,5,rep,name=inclusive_start_primary_key" json:"inclusive_start_primary_key,omitempty"`
	ExclusiveEndPrimaryKey   []*Column  `protobuf:"bytes,6,rep,name=exclusive_end_primary_key" json:"exclusive_end_primary_key,omitempty"`
	XXX_unrecognized         []byte     `json:"-"`
}

func (m *GetRangeRequest) Reset()                    { *m = GetRangeRequest{} }
func (m *GetRangeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRangeRequest) ProtoMessage()               {}
func (*GetRangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *GetRangeRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *GetRangeRequest) GetDirection() Direction {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return Direction_FORWARD
}

func (m *GetRangeRequest) GetColumnsToGet() []string {
	if m != nil {
		return m.ColumnsToGet
	}
	return nil
}

func (m *GetRangeRequest) GetLimit() int32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *GetRangeRequest) GetInclusiveStartPrimaryKey() []*Column {
	if m != nil {
		return m.InclusiveStartPrimaryKey
	}
	return nil
}

func (m *GetRangeRequest) GetExclusiveEndPrimaryKey() []*Column {
	if m != nil {
		return m.ExclusiveEndPrimaryKey
	}
	return nil
}

type GetRangeResponse struct {
	Consumed            *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	NextStartPrimaryKey []*Column         `protobuf:"bytes,2,rep,name=next_start_primary_key" json:"next_start_primary_key,omitempty"`
	Rows                []*Row            `protobuf:"bytes,3,rep,name=rows" json:"rows,omitempty"`
	XXX_unrecognized    []byte            `json:"-"`
}

func (m *GetRangeResponse) Reset()                    { *m = GetRangeResponse{} }
func (m *GetRangeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRangeResponse) ProtoMessage()               {}
func (*GetRangeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *GetRangeResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *GetRangeResponse) GetNextStartPrimaryKey() []*Column {
	if m != nil {
		return m.NextStartPrimaryKey
	}
	return nil
}

func (m *GetRangeResponse) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*ColumnSchema)(nil), "pb.ColumnSchema")
	proto.RegisterType((*ColumnValue)(nil), "pb.ColumnValue")
	proto.RegisterType((*Column)(nil), "pb.Column")
	proto.RegisterType((*Row)(nil), "pb.Row")
	proto.RegisterType((*TableMeta)(nil), "pb.TableMeta")
	proto.RegisterType((*Condition)(nil), "pb.Condition")
	proto.RegisterType((*CapacityUnit)(nil), "pb.CapacityUnit")
	proto.RegisterType((*ReservedThroughputDetails)(nil), "pb.ReservedThroughputDetails")
	proto.RegisterType((*ReservedThroughput)(nil), "pb.ReservedThroughput")
	proto.RegisterType((*ConsumedCapacity)(nil), "pb.ConsumedCapacity")
	proto.RegisterType((*CreateTableRequest)(nil), "pb.CreateTableRequest")
	proto.RegisterType((*CreateTableResponse)(nil), "pb.CreateTableResponse")
	proto.RegisterType((*UpdateTableRequest)(nil), "pb.UpdateTableRequest")
	proto.RegisterType((*UpdateTableResponse)(nil), "pb.UpdateTableResponse")
	proto.RegisterType((*DescribeTableRequest)(nil), "pb.DescribeTableRequest")
	proto.RegisterType((*DescribeTableResponse)(nil), "pb.DescribeTableResponse")
	proto.RegisterType((*ListTableRequest)(nil), "pb.ListTableRequest")
	proto.RegisterType((*ListTableResponse)(nil), "pb.ListTableResponse")
	proto.RegisterType((*DeleteTableRequest)(nil), "pb.DeleteTableRequest")
	proto.RegisterType((*DeleteTableResponse)(nil), "pb.DeleteTableResponse")
	proto.RegisterType((*GetRowRequest)(nil), "pb.GetRowRequest")
	proto.RegisterType((*GetRowResponse)(nil), "pb.GetRowResponse")
	proto.RegisterType((*ColumnUpdate)(nil), "pb.ColumnUpdate")
	proto.RegisterType((*UpdateRowRequest)(nil), "pb.UpdateRowRequest")
	proto.RegisterType((*UpdateRowResponse)(nil), "pb.UpdateRowResponse")
	proto.RegisterType((*PutRowRequest)(nil), "pb.PutRowRequest")
	proto.RegisterType((*PutRowResponse)(nil), "pb.PutRowResponse")
	proto.RegisterType((*DeleteRowRequest)(nil), "pb.DeleteRowRequest")
	proto.RegisterType((*DeleteRowResponse)(nil), "pb.DeleteRowResponse")
	proto.RegisterType((*RowInBatchGetRowRequest)(nil), "pb.RowInBatchGetRowRequest")
	proto.RegisterType((*TableInBatchGetRowRequest)(nil), "pb.TableInBatchGetRowRequest")
	proto.RegisterType((*BatchGetRowRequest)(nil), "pb.BatchGetRowRequest")
	proto.RegisterType((*RowInBatchGetRowResponse)(nil), "pb.RowInBatchGetRowResponse")
	proto.RegisterType((*TableInBatchGetRowResponse)(nil), "pb.TableInBatchGetRowResponse")
	proto.RegisterType((*BatchGetRowResponse)(nil), "pb.BatchGetRowResponse")
	proto.RegisterType((*PutRowInBatchWriteRowRequest)(nil), "pb.PutRowInBatchWriteRowRequest")
	proto.RegisterType((*UpdateRowInBatchWriteRowRequest)(nil), "pb.UpdateRowInBatchWriteRowRequest")
	proto.RegisterType((*DeleteRowInBatchWriteRowRequest)(nil), "pb.DeleteRowInBatchWriteRowRequest")
	proto.RegisterType((*TableInBatchWriteRowRequest)(nil), "pb.TableInBatchWriteRowRequest")
	proto.RegisterType((*BatchWriteRowRequest)(nil), "pb.BatchWriteRowRequest")
	proto.RegisterType((*RowInBatchWriteRowResponse)(nil), "pb.RowInBatchWriteRowResponse")
	proto.RegisterType((*TableInBatchWriteRowResponse)(nil), "pb.TableInBatchWriteRowResponse")
	proto.RegisterType((*BatchWriteRowResponse)(nil), "pb.BatchWriteRowResponse")
	proto.RegisterType((*GetRangeRequest)(nil), "pb.GetRangeRequest")
	proto.RegisterType((*GetRangeResponse)(nil), "pb.GetRangeResponse")
	proto.RegisterEnum("pb.ColumnType", ColumnType_name, ColumnType_value)
	proto.RegisterEnum("pb.RowExistenceExpectation", RowExistenceExpectation_name, RowExistenceExpectation_value)
	proto.RegisterEnum("pb.OperationType", OperationType_name, OperationType_value)
	proto.RegisterEnum("pb.Direction", Direction_name, Direction_value)
}

var fileDescriptor0 = []byte{
	// 1389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x58, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0xfe, 0xa9, 0x9b, 0xad, 0x23, 0x4b, 0xa1, 0x69, 0x3b, 0xbf, 0x1c, 0x27, 0xb1, 0xcb, 0x36,
	0xa9, 0xeb, 0x20, 0x4e, 0xe0, 0x00, 0x45, 0x90, 0xa2, 0x28, 0x7c, 0x61, 0x0c, 0xa1, 0x8e, 0x14,
	0x28, 0x72, 0x93, 0x00, 0x29, 0x08, 0x4a, 0x9c, 0xda, 0x44, 0x24, 0x92, 0x25, 0x87, 0xbe, 0x2c,
	0x5a, 0x74, 0xd7, 0x6e, 0xba, 0xe8, 0xa6, 0xdb, 0xbe, 0x51, 0xf7, 0x7d, 0x9b, 0x9e, 0x21, 0x87,
	0x12, 0x45, 0x8e, 0x2c, 0xb9, 0x80, 0x77, 0x9a, 0xe1, 0xb9, 0x7c, 0xe7, 0xf6, 0xcd, 0x8c, 0xa0,
	0xea, 0x50, 0x5f, 0x37, 0x5c, 0x6b, 0xdb, 0xf5, 0x1c, 0xea, 0x28, 0x39, 0xb7, 0xab, 0x3e, 0x84,
	0xa2, 0xe6, 0x79, 0x8e, 0xa7, 0x2c, 0x40, 0xa1, 0xe7, 0x98, 0xa4, 0x2e, 0x6d, 0xe4, 0x36, 0xcb,
	0xca, 0x2d, 0x98, 0x1b, 0x10, 0xdf, 0x37, 0x4e, 0x48, 0x3d, 0xb7, 0x21, 0x6d, 0x96, 0xd5, 0x17,
	0xb0, 0xb0, 0xef, 0xf4, 0x83, 0x81, 0xfd, 0xa6, 0x77, 0x4a, 0x06, 0x06, 0x13, 0xb7, 0x8d, 0x41,
	0x2c, 0x7e, 0x17, 0x0a, 0xf4, 0xd2, 0x65, 0xb2, 0xb9, 0xcd, 0xda, 0x4e, 0x6d, 0xdb, 0xed, 0x6e,
	0x47, 0xd2, 0x1d, 0xdc, 0x55, 0x7f, 0x91, 0xa0, 0x12, 0x2d, 0xbf, 0x33, 0xfa, 0x01, 0x19, 0x4a,
	0x4b, 0x22, 0x69, 0xa5, 0x0a, 0xc5, 0x33, 0xdd, 0xb2, 0x69, 0xe8, 0x38, 0xaf, 0xc8, 0x30, 0x7f,
	0xa6, 0xfb, 0xd4, 0xb3, 0xec, 0x93, 0x7a, 0x9e, 0x41, 0x51, 0x6a, 0x50, 0x3a, 0xd3, 0xbb, 0x8e,
	0xd3, 0xaf, 0x17, 0x70, 0x3d, 0x1f, 0x49, 0x98, 0x4e, 0xd0, 0xed, 0x93, 0x7a, 0x11, 0x77, 0xa4,
	0x68, 0xa7, 0x6b, 0xd9, 0x86, 0x77, 0x59, 0x2f, 0xe1, 0xce, 0x82, 0xfa, 0x25, 0x94, 0x22, 0x17,
	0x29, 0xe0, 0xf7, 0xd1, 0x19, 0xc3, 0x14, 0x22, 0xaf, 0xec, 0xdc, 0x1a, 0x61, 0x09, 0xa1, 0xaa,
	0xc7, 0x90, 0x6f, 0x3b, 0xe7, 0xca, 0xe7, 0xb0, 0xe4, 0x7a, 0xd6, 0x00, 0xed, 0xe9, 0x1f, 0xc9,
	0xa5, 0xde, 0x0b, 0x25, 0x7c, 0xb4, 0x91, 0x47, 0x25, 0x18, 0x29, 0x29, 0x0f, 0x60, 0xd1, 0xa0,
	0x08, 0xb6, 0x1b, 0x50, 0x32, 0x14, 0xcb, 0xa5, 0xc5, 0xd4, 0x97, 0x50, 0xee, 0x18, 0x88, 0xf7,
	0x15, 0xa1, 0x86, 0xa2, 0x00, 0x50, 0xb6, 0xd0, 0x13, 0xb8, 0x1e, 0x40, 0x25, 0xe1, 0x90, 0x5b,
	0x90, 0x47, 0x16, 0xa2, 0x2a, 0xa8, 0xdf, 0x40, 0x79, 0xdf, 0xb1, 0x4d, 0x8b, 0x5a, 0x8e, 0xad,
	0xec, 0x40, 0xd5, 0x73, 0xce, 0x75, 0x72, 0x61, 0xf9, 0x94, 0xd8, 0xbd, 0x38, 0xbf, 0x6b, 0x4c,
	0x0b, 0x83, 0xd0, 0xe2, 0x7d, 0xed, 0xc2, 0x25, 0x3d, 0x6a, 0x30, 0x1d, 0xf5, 0x11, 0x96, 0xd5,
	0x70, 0x8d, 0x9e, 0x45, 0x2f, 0x8f, 0x6d, 0x8b, 0xb2, 0xec, 0x78, 0xc4, 0x30, 0x51, 0x55, 0xda,
	0x2c, 0xb2, 0x52, 0x9c, 0x7b, 0x16, 0x8d, 0x7a, 0xa0, 0xa8, 0xfe, 0x25, 0xc1, 0x6a, 0x9b, 0xf8,
	0xc4, 0x3b, 0x23, 0x66, 0xe7, 0xd4, 0x73, 0x82, 0x93, 0x53, 0x37, 0xa0, 0x07, 0x18, 0x83, 0xd5,
	0xf7, 0x31, 0x47, 0xd5, 0x1e, 0x37, 0xa5, 0x07, 0x68, 0x2b, 0x74, 0x1f, 0x83, 0x4e, 0xfa, 0xb8,
	0x03, 0x4a, 0xdf, 0xf0, 0x29, 0xd6, 0xb8, 0x87, 0xbe, 0x7c, 0xa2, 0x53, 0x6b, 0x10, 0x15, 0x20,
	0x3f, 0xfc, 0x66, 0x92, 0xe4, 0xb7, 0x7c, 0xd8, 0x09, 0x9f, 0xc0, 0xaa, 0x1d, 0x0c, 0xba, 0xc4,
	0xd3, 0x9d, 0x1f, 0x86, 0x02, 0xbe, 0x4e, 0x1d, 0xd3, 0xb8, 0xc4, 0x56, 0xc8, 0x21, 0xc2, 0xaf,
	0x41, 0xc9, 0x02, 0x9c, 0x19, 0x99, 0xfa, 0x15, 0xc8, 0x98, 0x4e, 0x3f, 0x18, 0x10, 0x33, 0xde,
	0x9f, 0x5d, 0xb9, 0x0f, 0xca, 0x3e, 0x42, 0xa2, 0x24, 0xac, 0x6c, 0x9b, 0xfc, 0x18, 0x10, 0x9f,
	0x22, 0x68, 0x5e, 0xdc, 0x01, 0xa6, 0x89, 0xeb, 0x56, 0x99, 0xee, 0xa8, 0xfe, 0xcf, 0x60, 0xc9,
	0xe3, 0xa0, 0x75, 0x3a, 0x44, 0xcd, 0x3b, 0xf2, 0x76, 0x58, 0xbd, 0x4c, 0x4c, 0xea, 0x0a, 0x2c,
	0x8d, 0x79, 0xf3, 0x5d, 0x04, 0x4e, 0xd4, 0xef, 0x41, 0x39, 0x76, 0xcd, 0x34, 0x08, 0x51, 0x87,
	0xfd, 0x27, 0xaf, 0xef, 0x61, 0x69, 0xcc, 0x7c, 0xe4, 0x55, 0xd9, 0x83, 0x35, 0x81, 0x2d, 0xac,
	0x51, 0xd8, 0x19, 0x3c, 0xea, 0x7b, 0x62, 0x9b, 0xbc, 0x7d, 0xd4, 0x2d, 0x58, 0x3e, 0x20, 0x7e,
	0x0f, 0x47, 0x67, 0x2a, 0x76, 0xf5, 0x67, 0x58, 0x49, 0xc9, 0x72, 0x20, 0x33, 0x64, 0x7b, 0x0a,
	0xd6, 0xdc, 0x2c, 0x58, 0x15, 0x90, 0x8f, 0x70, 0x98, 0x92, 0x38, 0xd5, 0x4d, 0x58, 0x4c, 0xec,
	0x71, 0x3c, 0x4b, 0x50, 0x19, 0x81, 0x8f, 0xf8, 0xa2, 0x8c, 0x92, 0xca, 0x01, 0xe9, 0x93, 0xe9,
	0x35, 0x62, 0x45, 0x1e, 0x93, 0xe4, 0x45, 0xfe, 0x00, 0xd5, 0x43, 0x42, 0x71, 0xa4, 0xaf, 0xaa,
	0xef, 0xba, 0x88, 0x41, 0x92, 0x54, 0x75, 0x1b, 0x6a, 0x9c, 0xa0, 0x70, 0x84, 0xf4, 0x13, 0x42,
	0x71, 0xcc, 0x18, 0xbc, 0x26, 0xd4, 0x62, 0xeb, 0x3c, 0x8a, 0x87, 0x30, 0xdf, 0xe3, 0x63, 0xc1,
	0x73, 0xba, 0x1c, 0xd9, 0x49, 0x8d, 0xca, 0x32, 0xe4, 0x91, 0x80, 0x78, 0x0a, 0xe7, 0x38, 0xed,
	0x60, 0x4b, 0xf2, 0x93, 0x23, 0xea, 0x1c, 0x04, 0x96, 0x64, 0xff, 0x45, 0x26, 0xd6, 0x72, 0x89,
	0x17, 0xf2, 0x51, 0x78, 0x00, 0xc4, 0x0c, 0x9d, 0x1b, 0x67, 0x68, 0x46, 0x02, 0x02, 0x86, 0xfe,
	0x53, 0x02, 0x39, 0xb2, 0x3c, 0x25, 0x21, 0x1b, 0x50, 0xee, 0xc5, 0x5c, 0xc9, 0x31, 0x56, 0x79,
	0x18, 0x9c, 0x40, 0x53, 0x29, 0xcb, 0x67, 0x52, 0xf6, 0x48, 0xc4, 0xee, 0x85, 0x34, 0x37, 0x47,
	0x68, 0x90, 0x4c, 0x16, 0x13, 0xb8, 0xae, 0x97, 0x4a, 0xf5, 0x77, 0x09, 0xaa, 0xaf, 0x03, 0x7a,
	0xf3, 0x21, 0x3d, 0x98, 0x1c, 0x52, 0xf2, 0xc0, 0x7a, 0x0e, 0xb5, 0x18, 0xce, 0x35, 0x23, 0xb1,
	0x40, 0x8e, 0x7a, 0xf8, 0xc6, 0x63, 0x61, 0x19, 0x4f, 0xb8, 0xba, 0x26, 0xce, 0x17, 0xf0, 0x7f,
	0x54, 0x6b, 0xd8, 0x7b, 0x06, 0xed, 0x9d, 0x8e, 0x8f, 0x57, 0xca, 0x71, 0xe6, 0xd4, 0x57, 0x3d,
	0x58, 0x0d, 0x27, 0x54, 0xa8, 0x2d, 0x0a, 0xf6, 0x0b, 0x3c, 0x66, 0x9d, 0xf3, 0xf8, 0x66, 0x10,
	0x9f, 0xd0, 0x42, 0xf5, 0x49, 0x63, 0xba, 0x0f, 0x8a, 0x40, 0xfa, 0x31, 0x94, 0x42, 0x67, 0xf1,
	0xdd, 0xe4, 0xde, 0x90, 0xfc, 0x44, 0xc6, 0xd5, 0x5f, 0x25, 0xa8, 0x67, 0x1d, 0x0f, 0xc9, 0xab,
	0x68, 0xf9, 0xba, 0xf3, 0x31, 0xc4, 0x3c, 0xff, 0xa2, 0x40, 0x3d, 0xbc, 0xbb, 0xd5, 0xa1, 0x48,
	0xd8, 0x7d, 0x31, 0xbc, 0x12, 0x54, 0x76, 0xca, 0xcc, 0x7e, 0x74, 0x81, 0x4c, 0x26, 0x3a, 0x9a,
	0xd5, 0x2b, 0x59, 0xa2, 0x10, 0x8a, 0x0c, 0x59, 0xe2, 0x03, 0xdc, 0x11, 0xc1, 0xe4, 0x50, 0x44,
	0x39, 0xdc, 0x1a, 0xcb, 0xe1, 0x5d, 0x71, 0x0e, 0x39, 0x63, 0x6a, 0xb0, 0x24, 0x32, 0xbb, 0x9d,
	0xca, 0xd6, 0xfd, 0x49, 0xd9, 0xe2, 0x66, 0x7e, 0x93, 0xe0, 0x6e, 0x34, 0x06, 0xfc, 0xfb, 0x5b,
	0x76, 0x3b, 0x4a, 0xa4, 0x7f, 0xac, 0x89, 0xa5, 0x19, 0x9a, 0x38, 0x37, 0xdb, 0x40, 0x66, 0x7b,
	0xfd, 0x0f, 0x09, 0xd6, 0x87, 0xf4, 0x72, 0x73, 0x68, 0x1e, 0x4d, 0x46, 0x93, 0x65, 0x3c, 0x13,
	0xd6, 0x87, 0xf3, 0x77, 0x63, 0x90, 0xd4, 0x7f, 0x24, 0x58, 0x4b, 0xd6, 0x28, 0xed, 0x42, 0xd4,
	0x2b, 0x3b, 0x30, 0xcf, 0x0e, 0xf9, 0x44, 0xbf, 0x6c, 0x30, 0x8b, 0x57, 0xd6, 0xf2, 0x39, 0x54,
	0x82, 0x30, 0xae, 0x48, 0x2d, 0x0a, 0xfa, 0x53, 0xa6, 0x36, 0x2d, 0xef, 0xa8, 0x69, 0x86, 0x79,
	0x88, 0x34, 0x0b, 0x23, 0xcd, 0x29, 0xe9, 0x51, 0x0f, 0x61, 0x59, 0x68, 0xf1, 0x49, 0xaa, 0x51,
	0xd7, 0xd3, 0x8d, 0x9a, 0x36, 0xe4, 0xc3, 0x1d, 0x91, 0x97, 0x1b, 0x9d, 0x6c, 0xf5, 0x6f, 0x1c,
	0x0f, 0x31, 0xa8, 0x2b, 0xc6, 0xf8, 0x69, 0xa6, 0x34, 0xf7, 0xc7, 0x47, 0x39, 0x63, 0xe5, 0x99,
	0xa8, 0x30, 0x33, 0x28, 0x65, 0x6b, 0x32, 0x45, 0x49, 0x6d, 0xc0, 0x8a, 0xd8, 0xda, 0xd3, 0x54,
	0x3d, 0x36, 0x26, 0xd7, 0x83, 0x9b, 0xc2, 0xdc, 0xdc, 0x62, 0x6c, 0x62, 0xd8, 0x27, 0x64, 0xca,
	0x31, 0x68, 0x5a, 0x1e, 0xbe, 0xcf, 0xe2, 0x63, 0xb0, 0x16, 0x0d, 0xc8, 0x41, 0xbc, 0x39, 0xe9,
	0x40, 0x60, 0x8f, 0xb5, 0xbe, 0x35, 0xc0, 0x07, 0x4a, 0x21, 0x7c, 0xbb, 0x3d, 0x81, 0x35, 0x7c,
	0x60, 0xf5, 0x03, 0xdf, 0x3a, 0x23, 0xf8, 0x7e, 0x36, 0x3c, 0xaa, 0x27, 0xe7, 0xaa, 0x98, 0x19,
	0xf5, 0xc7, 0xb0, 0x4a, 0x2e, 0x62, 0x05, 0x62, 0x9b, 0x63, 0xe2, 0xa5, 0xcc, 0x18, 0xfe, 0x04,
	0xf2, 0x28, 0x9e, 0x6b, 0x5e, 0x14, 0xb7, 0xe0, 0xb6, 0x4d, 0x2e, 0xa8, 0x00, 0x56, 0x96, 0x81,
	0x56, 0x38, 0xcd, 0x47, 0x65, 0x8e, 0xcf, 0x8b, 0x2d, 0x13, 0x20, 0xf1, 0x9f, 0x41, 0x05, 0xe6,
	0x1a, 0xcd, 0x97, 0xfa, 0xab, 0x46, 0x53, 0xfe, 0xdf, 0x70, 0xb1, 0xfb, 0x4e, 0x96, 0xa2, 0x45,
	0x47, 0x3b, 0xd4, 0xda, 0x72, 0x0e, 0xf3, 0x5d, 0x7a, 0xd3, 0x69, 0x37, 0x9a, 0x87, 0x72, 0x9e,
	0x7d, 0xd8, 0x6b, 0xb5, 0x8e, 0xb4, 0xdd, 0xa6, 0x5c, 0x60, 0x1f, 0x0e, 0x5a, 0xc7, 0x7b, 0x47,
	0x9a, 0x5c, 0x64, 0xbf, 0xf7, 0x1a, 0xcd, 0xdd, 0xf6, 0x7b, 0xb9, 0xb4, 0xf5, 0x2a, 0xbc, 0x14,
	0x88, 0x5e, 0xce, 0x4c, 0xac, 0x71, 0xd8, 0x6c, 0xb5, 0x35, 0xf4, 0x28, 0xc3, 0x82, 0xf6, 0xee,
	0xb5, 0xb6, 0xdf, 0xd1, 0xb5, 0x77, 0x8d, 0x37, 0x1d, 0x74, 0xbb, 0x0c, 0x32, 0xdf, 0x69, 0xb6,
	0xe2, 0xdd, 0xdc, 0xd6, 0x67, 0x50, 0x1d, 0xbf, 0xea, 0xce, 0x41, 0xfe, 0xf5, 0x31, 0x93, 0x67,
	0x00, 0xb4, 0x23, 0xad, 0xa3, 0xa1, 0xd4, 0x43, 0x28, 0x8f, 0xaa, 0x8d, 0x30, 0x5f, 0xb6, 0xda,
	0x6f, 0x77, 0xdb, 0x07, 0xe8, 0x67, 0x01, 0xe6, 0xf7, 0x76, 0xf7, 0xbf, 0x0d, 0x57, 0xd2, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x00, 0x1e, 0x5a, 0x17, 0xce, 0x11, 0x00, 0x00,
}
